/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sikar.view;

import com.sikar.dao.CiriMinatBakatDAO;
import com.sikar.dao.CiriMinatBakatDAOMySQL;
import com.sikar.dao.HasilDAO;
import com.sikar.dao.HasilDAOMySQL;
import com.sikar.model.CiriMinatBakat;
import com.sikar.model.HasilJoin;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin01
 */
public class HasilFrame extends javax.swing.JFrame {
    private final HasilDAO hasilDAO;
    private List<HasilJoin> recHasilDAOs = new ArrayList<>();
    /**
     * Creates new form TambahGejalaFrame
     */
    public HasilFrame() throws SQLException {
        initComponents();
        hasilDAO = new HasilDAOMySQL();
        initStatus();

        
    }

    public void loadHasil() throws SQLException {
        recHasilDAOs = hasilDAO.getHasilByUserId("test");
    }

    public void tableFill() {
    List<HasilJoin> hasilJoins = recHasilDAOs;  // Assuming recHasilDAOs is a List
    int dataLength = hasilJoins.size();

    // Prepare data for the table model
    Object[][] data = new Object[dataLength][5];  // Only include necessary columns
    for (int i = 0; i < dataLength; i++) {
      HasilJoin hasilJoin = hasilJoins.get(i);
      data[i][0] = i + 1;  // Start index at 1 for "No" column
      data[i][1] = hasilJoin.getId_user();
      data[i][2] = hasilJoin.getNama();
      data[i][3] = hasilJoin.getNama_kecerdasan();
      data[i][4] = hasilJoin.getKecocokan();
    }

    // Define table headers
    String[] judul = {"No", "ID Pengguna", "Nama", "Kecerdasan", "Kecocokan"};

    // Set the table model
    tabelCiriMinatBakat.setModel(new DefaultTableModel(data, judul));
}


    

    void initStatus() throws SQLException {
        loadHasil();
        tableFill();
    }

    void refresh_page() throws SQLException {
        this.dispose();
        HasilFrame f = new HasilFrame();
        f.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        bgBlue = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        TambahGejala = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        DataCiriMinatBakatBox = new javax.swing.JPanel();
        DataGejala = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelCiriMinatBakat = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        txtCariNama = new javax.swing.JTextField();
        btnCari1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgBlue.setBackground(new java.awt.Color(5, 101, 201));

        navbar.setBackground(new java.awt.Color(254, 254, 254));

        TambahGejala.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        TambahGejala.setText("Tambah Ciri Minat Bakat");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TambahGejala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 460, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(36, 36, 36))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahGejala)
                    .addComponent(btnKembali))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DataCiriMinatBakatBox.setBackground(new java.awt.Color(254, 254, 254));

        DataGejala.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        DataGejala.setText("Hasil ");

        tabelCiriMinatBakat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelCiriMinatBakat);

        btnCari.setText("Cari ID");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtCari.setText("Cari");

        txtCariNama.setText("Cari");

        btnCari1.setText("Cari Nama");
        btnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataCiriMinatBakatBoxLayout = new javax.swing.GroupLayout(DataCiriMinatBakatBox);
        DataCiriMinatBakatBox.setLayout(DataCiriMinatBakatBoxLayout);
        DataCiriMinatBakatBoxLayout.setHorizontalGroup(
            DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                        .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                                .addComponent(DataGejala, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addGap(20, 20, 20))
                    .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                                .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        DataCiriMinatBakatBoxLayout.setVerticalGroup(
            DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataCiriMinatBakatBoxLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(DataGejala)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataCiriMinatBakatBoxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCari)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(DataCiriMinatBakatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgBlueLayout = new javax.swing.GroupLayout(bgBlue);
        bgBlue.setLayout(bgBlueLayout);
        bgBlueLayout.setHorizontalGroup(
            bgBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBlueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DataCiriMinatBakatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgBlueLayout.setVerticalGroup(
            bgBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBlueLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(DataCiriMinatBakatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserFrame f = new UserFrame();
        f.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed
    
    private void updateTable(List<HasilJoin> hasilJoins) {
  // Prepare data for the table model
  Object[][] data = new Object[hasilJoins.size()][5];
  for (int i = 0; i < data.length; i++) {
    HasilJoin hasilJoin = hasilJoins.get(i);
    data[i][0] = i + 1;
    data[i][1] = hasilJoin.getId_user();
    data[i][2] = hasilJoin.getNama();
    data[i][3] = hasilJoin.getNama_kecerdasan();
    data[i][4] = hasilJoin.getKecocokan();
  }

  // Define table headers
  String[] judul = {"No", "ID Pengguna", "Nama", "Kecerdasan", "Kecocokan"};

  // Create a DefaultTableModel
  DefaultTableModel tableModel = new DefaultTableModel(data, judul);

  // Set the table model for the JTable
  tabelCiriMinatBakat.setModel(tableModel);

  // Optionally: Clear previous selection
  tabelCiriMinatBakat.getSelectionModel().clearSelection();
}

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            String cari = txtCari.getText();
            recHasilDAOs = hasilDAO.getHasilByUserId(cari);
            updateTable(recHasilDAOs);
        } catch (SQLException ex) {
            Logger.getLogger(HasilFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
        
        try {
            String cari = txtCari.getText();
            recHasilDAOs = hasilDAO.getHasilByNama(cari);
            updateTable(recHasilDAOs);
        } catch (SQLException ex) {
            Logger.getLogger(HasilFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCari1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HasilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HasilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HasilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HasilFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HasilFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(HasilFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataCiriMinatBakatBox;
    private javax.swing.JLabel DataGejala;
    private javax.swing.JLabel TambahGejala;
    private javax.swing.JPanel bgBlue;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel navbar;
    private javax.swing.JTable tabelCiriMinatBakat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCariNama;
    // End of variables declaration//GEN-END:variables
}
