
package com.sikar.view;

import com.sikar.dao.AturanDAO;
import com.sikar.dao.AturanDAOMySQL;
import com.sikar.dao.JawabanUserDAO;
import com.sikar.dao.JawabanUserDAOMySQL;
import com.sikar.model.Aturan;
import com.sikar.model.JawabanUser;
import com.sikar.model.Orang;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Afghan
 */
public class PertanyaanDialog extends javax.swing.JDialog {

     private final JawabanUserDAO jawabanUserDAO;
     private final AturanDAO aturanDAO;
     public List<JawabanUser> recJawabanUser = new ArrayList<>();
     private String userId;
    public PertanyaanDialog(Frame parent, boolean modal, String userId) {
        super(parent, modal);
        initComponents();
        jawabanUserDAO = new JawabanUserDAOMySQL();
        aturanDAO = new AturanDAOMySQL();
        this.userId = userId; // Set userId in the constructor
        System.out.println("userId: " + this.userId); // Now prints the correct userId value
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        txtKodeCiri = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPosPerNow = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPertanyaan = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        rbTidak = new javax.swing.JRadioButton();
        rbIya = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txtPertanyaan = new javax.swing.JLabel();

        txtKodeCiri.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Pertanyaan");

        txtPosPerNow.setText("n");

        jLabel4.setText("dari");

        txtTotalPertanyaan.setText("n");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        rbGroup.add(rbTidak);
        rbTidak.setText("Tidak");
        rbTidak.setName("T"); // NOI18N

        rbGroup.add(rbIya);
        rbIya.setText("Iya");
        rbIya.setName("Y"); // NOI18N
        rbIya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIyaActionPerformed(evt);
            }
        });

        txtPertanyaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPertanyaan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPertanyaan.setText("Pertanyaan-nya disini");
        txtPertanyaan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPertanyaan.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtPertanyaanComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(rbIya, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPosPerNow, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPertanyaan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPosPerNow)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPertanyaan)
                    .addComponent(btnKeluar))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTidak)
                    .addComponent(rbIya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        rbIya.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        UserFrame u = new UserFrame();
        u.txtId.setText(userId);
        
        if(rbIya.isSelected() || rbTidak.isSelected()){
            nextProsesPertanyaan(u);
            this.dispose();



            int no = u.index+1;
            if(no == u.recCiriMinatBakat.size()){
                u.tampilkanPertanyaan("Selesai");
                try {
                    System.out.println(cekKesamaanJawabanDenganAturan());
                } catch (SQLException ex) {
                    Logger.getLogger(PertanyaanDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
;
                
            }else{
                u.tampilkanPertanyaan("Next");
            }
            
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Tolong diisi");
        }
        
        
       
        
    }//GEN-LAST:event_btnNextActionPerformed
    
    public void nextProsesPertanyaan(UserFrame u) {
        u.index +=1;
        String jawaban = null;
            if(rbIya.isSelected()){
                jawaban = "Y";
            }else if(rbTidak.isSelected()){
                jawaban = "N";
            }
         try {
             jawabanUserDAO.insertJawabanUser(userId, Integer.parseInt(txtKodeCiri.getText()), jawaban );
         } catch (SQLException ex) {
             Logger.getLogger(PertanyaanDialog.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    
  public List<Aturan> cekKesamaanJawabanDenganAturan() throws SQLException {
        List<Aturan> semuaAturan = aturanDAO.getAturanKecerdasanWithJurusan();
        List<String> semuaJawaban = jawabanUserDAO.getAllJawabanUserByUserIdAndStatus(userId, "Y");

        // Map untuk menyimpan jumlah kecocokan setiap aturan dengan jawaban pengguna
        Map<Aturan, Integer> kecocokanAturan = new HashMap<>();
        System.out.println(semuaAturan);

        // Periksa setiap aturan
        for (Aturan aturan : semuaAturan) {
            String[] kriteriaAturan = aturan.getJika().split(","); // Pisahkan string menjadi array string
            int kecocokan = 0;

            // Periksa setiap jawaban
            for (String jawaban : semuaJawaban) {
                if (Arrays.asList(kriteriaAturan).contains(jawaban)) {
                    kecocokan++; // Tambahkan jumlah kecocokan
                }
            }

            // Simpan jumlah kecocokan aturan
            kecocokanAturan.put(aturan, kecocokan);
        }

        // Sorting berdasarkan jumlah kecocokan, dengan Comparator untuk membandingkan nilai
        List<Map.Entry<Aturan, Integer>> sortedList = new ArrayList<>(kecocokanAturan.entrySet());
        sortedList.sort((entry1, entry2) -> entry2.getValue().compareTo(entry1.getValue()));

        // Ambil 3 aturan teratas
        List<Aturan> topThreeAturan = new ArrayList<>();
        for (int i = 0; i < Math.min(3, sortedList.size()); i++) {
            topThreeAturan.add(sortedList.get(i).getKey());
            System.out.println("Aturan " + sortedList.get(i).getKey().getKode_aturan()+ ": " + sortedList.get(i).getValue() + " kecocokan");
        }
        
         // Display top three rules using JOptionPane
        String message = "Hasil Top 3 Aturan: \n\n";
        for (int i = 0; i < Math.min(3, sortedList.size()); i++) {
            Aturan aturan = sortedList.get(i).getKey();
            int kecocokan = sortedList.get(i).getValue();

            message += "Aturan " + aturan.getKode_aturan() + ": " + kecocokan + " Kecocokan\n";
            message += "Jika: " + aturan.getJika() + "\n";
            message += "Maka: " + aturan.getMaka() + "\n\n";
            message +=  aturan.getKecerdasanMinat().getNama_kecerdasan() + "\n\n\n";
        }
         JOptionPane.showMessageDialog(null, message, "Top 3 Aturan", JOptionPane.INFORMATION_MESSAGE);

        return topThreeAturan;
    }







    
    public void backProsesPertanyaan(UserFrame u) {
        u.index -=1;
    }
    
    private void txtPertanyaanComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtPertanyaanComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPertanyaanComponentAdded

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        UserFrame u = new UserFrame();
        u.txtId.setText(userId);
        if (u.index > 0) {
            backProsesPertanyaan(u);
        u.tampilkanPertanyaan("Next");
    } else {
        // Handle the case where there's no previous question (index = 0)
        // You might want to display a message or take appropriate action
        System.out.println("No previous question available");
    }

    this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbIyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIyaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    private javax.swing.JButton btnKeluar;
    public javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup rbGroup;
    private javax.swing.JRadioButton rbIya;
    private javax.swing.JRadioButton rbTidak;
    public javax.swing.JLabel txtKodeCiri;
    public javax.swing.JLabel txtPertanyaan;
    public javax.swing.JLabel txtPosPerNow;
    public javax.swing.JLabel txtTotalPertanyaan;
    // End of variables declaration//GEN-END:variables
}
