
package com.sikar.view;

import com.sikar.dao.AturanDAO;
import com.sikar.dao.AturanDAOMySQL;
import com.sikar.dao.HasilDAO;
import com.sikar.dao.HasilDAOMySQL;
import com.sikar.dao.JawabanUserDAO;
import com.sikar.dao.JawabanUserDAOMySQL;
import com.sikar.model.Aturan;
import com.sikar.model.Hasil;
import com.sikar.model.JawabanUser;
import com.sikar.model.Orang;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Afghan
 */
public class PertanyaanDialog extends javax.swing.JDialog {

    private final JawabanUserDAO jawabanUserDAO;
    private final AturanDAO aturanDAO;
    public List<JawabanUser> recJawabanUser = new ArrayList<>();
    private String userId;
    private DataDiriForm dataDiriForm;
    private int currentQuestionIndex = 0;
    
    public PertanyaanDialog(Frame parent, boolean modal, String userId) {
        super(parent, modal);
        initComponents();
        jawabanUserDAO = new JawabanUserDAOMySQL();
        aturanDAO = new AturanDAOMySQL();
        this.userId = userId;
        dataDiriForm = new DataDiriForm();
        dataDiriForm.txtId.setText(userId);
        loadPertanyaan();
        System.out.println("userId: " + this.userId);
    }
    
    private void loadPertanyaan() {
        if (currentQuestionIndex < dataDiriForm.recCiriMinatBakat.size()) {
            txtPertanyaan.setText(dataDiriForm.recCiriMinatBakat.get(currentQuestionIndex).getPertanyaan());
            txtKodeCiri.setText(dataDiriForm.recCiriMinatBakat.get(currentQuestionIndex).getKodeCiri());
            txtPosPerNow.setText(String.valueOf(currentQuestionIndex + 1));
            txtTotalPertanyaan.setText(String.valueOf(dataDiriForm.recCiriMinatBakat.size()));
        } else {
            txtPertanyaan.setText("Selesai");
            txtKodeCiri.setText("");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        txtKodeCiri = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPosPerNow = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalPertanyaan = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        rbTidak = new javax.swing.JRadioButton();
        rbIya = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txtPertanyaan = new javax.swing.JLabel();

        txtKodeCiri.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Pertanyaan");

        txtPosPerNow.setText("n");

        jLabel4.setText("dari");

        txtTotalPertanyaan.setText("n");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        rbGroup.add(rbTidak);
        rbTidak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbTidak.setText("Tidak");
        rbTidak.setName("T"); // NOI18N
        rbTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTidakActionPerformed(evt);
            }
        });

        rbGroup.add(rbIya);
        rbIya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbIya.setText("Iya");
        rbIya.setName("Y"); // NOI18N
        rbIya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIyaActionPerformed(evt);
            }
        });

        txtPertanyaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPertanyaan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtPertanyaan.setText("Pertanyaan-nya disini");
        txtPertanyaan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPertanyaan.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtPertanyaanComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtPertanyaan, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPosPerNow, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalPertanyaan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(btnKeluar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(rbIya, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPosPerNow)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalPertanyaan)
                    .addComponent(btnKeluar))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIya)
                    .addComponent(rbTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        rbIya.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (rbIya.isSelected() || rbTidak.isSelected()) {
            nextProsesPertanyaan();
            currentQuestionIndex++;
            if (currentQuestionIndex >= dataDiriForm.recCiriMinatBakat.size()) {
                try {
                    System.out.println(cekKesamaanJawabanDenganAturan());
                } catch (SQLException ex) {
                    Logger.getLogger(PertanyaanDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                loadPertanyaan();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tolong diisi");
        }
    }//GEN-LAST:event_btnNextActionPerformed
    
    private void nextProsesPertanyaan() {
        String jawaban = rbIya.isSelected() ? "Y" : "N";
        try {
            jawabanUserDAO.insertJawabanUser(userId, Integer.parseInt(txtKodeCiri.getText()), jawaban);
        } catch (SQLException ex) {
            Logger.getLogger(PertanyaanDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
  public List<Aturan> cekKesamaanJawabanDenganAturan() throws SQLException {
        List<Aturan> semuaAturan = aturanDAO.getAturanKecerdasanWithJurusan();
        List<String> semuaJawaban = jawabanUserDAO.getAllJawabanUserByUserIdAndStatus(userId, "Y");

        Map<Aturan, Integer> kecocokanAturan = new HashMap<>();
        System.out.println(semuaAturan);

        for (Aturan aturan : semuaAturan) {
            String[] kriteriaAturan = aturan.getJika().split(",");
            int kecocokan = 0;

            for (String jawaban : semuaJawaban) {
                if (Arrays.asList(kriteriaAturan).contains(jawaban)) {
                    kecocokan++;
                }
            }

            kecocokanAturan.put(aturan, kecocokan);
        }

        List<Map.Entry<Aturan, Integer>> sortedList = new ArrayList<>(kecocokanAturan.entrySet());
        sortedList.sort((entry1, entry2) -> entry2.getValue().compareTo(entry1.getValue()));

        List<Aturan> topThreeAturan = new ArrayList<>();
        String message = "Hasil Aturan: \n\n";
        for (int i = 0; i < Math.min(5, sortedList.size()); i++) {
            Aturan aturan = sortedList.get(i).getKey();
            int kecocokan = sortedList.get(i).getValue();

            message += "Aturan " + aturan.getKode_aturan() + ": " + kecocokan + " Kecocokan\n";
            message += "Jika: " + aturan.getJika() + "\n";
            message += "Maka: " + aturan.getMaka() + "\n\n";
            message += aturan.getKecerdasanMinat().getNama_kecerdasan() + "\n\n\n";

            topThreeAturan.add(aturan);
        }
        JOptionPane.showMessageDialog(null, message, "Top 3 Aturan", JOptionPane.INFORMATION_MESSAGE);
        HasilDAO hasilDAO = new HasilDAOMySQL();
    
        // Simpan aturan yang memiliki kecocokan lebih dari atau sama dengan 4 ke dalam database
        for (Map.Entry<Aturan, Integer> entry : kecocokanAturan.entrySet()) {
            if (entry.getValue() >= 4) {
                Hasil hasil = new Hasil(userId, Integer.parseInt(entry.getKey().getMaka()), entry.getValue());
                hasilDAO.insertHasil(hasil);
            }
        }
        return topThreeAturan;
    }







    
    
    private void txtPertanyaanComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtPertanyaanComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPertanyaanComponentAdded

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         if (currentQuestionIndex > 0) {
            currentQuestionIndex--;
            loadPertanyaan();
        } else {
            System.out.println("No previous question available");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbIyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIyaActionPerformed

    private void rbTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    private javax.swing.JButton btnKeluar;
    public javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup rbGroup;
    private javax.swing.JRadioButton rbIya;
    private javax.swing.JRadioButton rbTidak;
    public javax.swing.JLabel txtKodeCiri;
    public javax.swing.JLabel txtPertanyaan;
    public javax.swing.JLabel txtPosPerNow;
    public javax.swing.JLabel txtTotalPertanyaan;
    // End of variables declaration//GEN-END:variables
}
